### ISSUE TITLE
ERROR: The OpenGL functionality tests failed!

### ISSUE THREAD

**Issue by pigeonshome** [chschnell/build-qt5-rpi#1] opened 2018-01-19 14:25 UTC
Raspberry Pi 3
Raspberry Pi OS: 2017-11-29-raspbian-stretch-lite
Host OS: debian-9.3.0-i386

`../build-qt5-rpi/build-qt5-rpi.sh -s ../qt-everywhere-opensource-src-5.9.3 init config build install`

```
Note: Dropped compiler flags '-pthread' when detecting library 'glib'.

Note: No wayland-egl support detected. Cross-toolkit compatibility disabled.

Note: Dropped compiler flags '-pthread' when detecting library 'gstreamer'.

Note: Dropped compiler flags '-pthread' when detecting library 'gstreamer_app'.

ERROR: Feature 'opengles2' was enabled, but the pre-condition 'config.win32 || (!config.watchos && !features.opengl-desktop && libs.opengl_es2)' failed.

ERROR: The OpenGL functionality tests failed!
You might need to modify the include and library search paths by editing QMAKE_INCDIR_OPENGL[_ES2],
QMAKE_LIBDIR_OPENGL[_ES2] and QMAKE_LIBS_OPENGL[_ES2] in the mkspec for your platform.

Check config.log for details.
++ exit
+ exit_handler
+ '[' false = false ']'
+ echo_fail '*** Build failed'
+ set +o xtrace
[build-qt5-rpi] 00:10:11 *** Build failed
```

**Comment by chschnell** [comment] 2018-01-19 16:29
Qt was not able to find the Raspberry EGLFS (OpenGL ES in fullscreen mode) libraries in your sysroot.

Take a look at the "QPA backends" section in your `build/config.summary`, you should find exactly this:

```
QPA backends:
  DirectFB ............................... no
  EGLFS .................................. yes
  EGLFS details:
    EGLFS i.Mx6 .......................... no
    EGLFS i.Mx6 Wayland .................. no
    EGLFS EGLDevice ...................... no
    EGLFS GBM ............................ no
    EGLFS Mali ........................... no
    EGLFS Raspberry Pi ................... yes
    EGL on X11 ........................... no
  LinuxFB ................................ yes
  VNC .................................... yes
  Mir client ............................. no
  X11:
    Using system-provided XCB libraries .. no
    EGL on X11 ........................... no
    Xinput2 .............................. no
    XCB XKB .............................. yes
    XLib ................................. yes
    XCB render ........................... yes
    XCB GLX .............................. no
    XCB Xlib ............................. no
    Using system-provided xkbcommon ...... no
```

Does it say "yes" for "EGLFS Raspberry Pi"? If not (or when you cannot find this entry at all), it means that something is wrong with your Pi or with your sysroot.

The contents of `sysroot/opt/vc/lib` should look like this:

```
libbcm_host.so    libdebug_sym_static.a  libGLESv2_static.a     libmmal_vc_client.so  libvcos.so
libbrcmEGL.so     libdtovl.so            libkhrn_client.a       libopenmaxil.so       libvcsm.so
libbrcmGLESv2.so  libEGL.so              libkhrn_static.a       libOpenVG.so          libWFC.so
libbrcmOpenVG.so  libEGL_static.a        libmmal_components.so  libvcfiled_check.a    pkgconfig
libbrcmWFC.so     libelftoolchain.so     libmmal_core.so        libvchiq_arm.so       plugins
libcontainers.so  libGLESv1_CM.so        libmmal.so             libvchostif.a
libdebug_sym.so   libGLESv2.so           libmmal_util.so        libvcilcs.a
```
If not, did you run `rpi-update` on your Pi? Perhaps you pulled in the mesa libraries, I can't remember but I think this could also cause Qt to fail detecting the Raspberry EGLFS libraries. Both issues are mentioned in  `README.md`.

I just started a fresh build (clean host and clean pi) on a Amd64 host (shouldn't make a difference), it works as it should.

**Comment by pigeonshome** [comment] 2018-01-23 09:04
The mesa libraries were causing the error.
Now the error:

```
Makefile:200: recipe for target 'sub-------3rdparty-mapbox-gl-native-make_first' failed
make[4]: *** [sub-------3rdparty-mapbox-gl-native-make_first] Error 2
...
Makefile:70: recipe for target 'sub-geoservices-make_first' failed
make[3]: *** [sub-geoservices-make_first] Error 2
...
Makefile:204: recipe for target 'sub-plugins-make_first' failed
make[2]: *** [sub-plugins-make_first] Error 2
...
Makefile:46: recipe for target 'sub-src-make_first' failed
make[1]: *** [sub-src-make_first] Error 2

Makefile:729: recipe for target 'module-qtlocation-make_first' failed
make: *** [module-qtlocation-make_first] Error 2
...
++ exit
+ exit_handler
+ '[' false = false ']'
+ echo_fail '*** Build failed'
+ set +o xtrace
[build-qt5-rpi] 02:51:00 *** Build failed
```

**Comment by chschnell** [comment] 2018-01-26 11:22
Sorry but I can't tell from this short snippet. Again, your bug is not reproducable for me, at least like this. Please tell me what you do differently from or additionally to my instructions in README.md.

**Comment by chschnell** [comment] 2018-02-20 08:23
Closing due to lack of reproducability.

**Closed as completed by chschnell** 2018-02-20 08:23 UTC
Labels: wontfix
